Renamed images backup file
MaRDI4NFDI/docker-backup pull request #10
Opened 2022-03-16 17:44 UTC by aot29

# MaRDI Pull Request

**Changes**:
- Renamed images backup file to images_XXX
- 
-  

**Instructions for PR review**:
- [ ] Conceptual Review (Logic etc...) 
- [ ] Code Review (Review your implementation) 
- [ ] Checkout (Test changes locally) 

**Checklist for this PR**: 
- [ ] [Reviewers and Assignee specified.](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)
- [ ] [All related issues are linked.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

2022-03-17 09:42 UTC, Hyper-Node requested changes

2022-03-17 09:42 UTC, Hyper-Node commented on backup.sh
>  files_dump() {
name images_dump and update references, if this is only for images

2022-03-17 09:42 UTC, Hyper-Node commented on backup.sh
>      printf "Files backup\n"
"Images backup\n"

2022-03-17 17:39 UTC, aot29 commented on backup.sh
>      printf "Files backup\n"
It's not only for images. If you would upload a pdf, it would end up in here too,.

2022-03-21 14:21 UTC, Hyper-Node approved these changes

2022-03-21 14:21 UTC, merged